// Copyright 2024, Evan Palmer
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#pragma once

#include <string>

#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "geometry_msgs/msg/wrench.hpp"
#include "geometry_msgs/msg/wrench_stamped.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp/qos.hpp"
#include "rclcpp_components/register_node_macro.hpp"
#include "rclcpp_lifecycle/lifecycle_node.hpp"

// auto-generated by generate_parameter_library
#include "message_transforms_parameters.hpp"

namespace m2m::transforms
{

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

class MessageTransforms : public rclcpp_lifecycle::LifecycleNode
{
public:
  explicit MessageTransforms(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  auto on_configure(const rclcpp_lifecycle::State & state) -> CallbackReturn override;

  auto on_activate(const rclcpp_lifecycle::State & state) -> CallbackReturn override;

private:
  auto transform_message(std::shared_ptr<geometry_msgs::msg::Pose> & message) -> void;

  auto transform_message(std::shared_ptr<geometry_msgs::msg::Twist> & message) -> void;

  auto transform_message(std::shared_ptr<geometry_msgs::msg::Wrench> & message) -> void;

  auto transform_message(std::shared_ptr<geometry_msgs::msg::PoseStamped> & message) -> void;

  auto transform_message(std::shared_ptr<geometry_msgs::msg::TwistStamped> & message) -> void;

  auto transform_message(std::shared_ptr<geometry_msgs::msg::WrenchStamped> & message) -> void;

  auto transform_message(std::shared_ptr<nav_msgs::msg::Odometry> & message) -> void;

  std::vector<std::shared_ptr<rclcpp::SubscriptionBase>> subscriptions_;
  std::vector<std::shared_ptr<rclcpp::PublisherBase>> publishers_;

  std::shared_ptr<message_transforms::ParamListener> param_listener_;
  message_transforms::Params params_;
};

}  // namespace m2m::transforms

RCLCPP_COMPONENTS_REGISTER_NODE(m2m::transforms::MessageTransforms)
